GET http://localhost:3001/api/events

###

GET https://calendar-rest-api.herokuapp.com/api/events/5cc2cceae090b621d184ed0d

###

POST http://localhost:3001/api/events
Content-Type: application/json

{
  "nam": "Kesdaasddasasddsasdt ",
  "date": "27.04.2019 03:00",
  "durationInHours": 3
}

###

PUT http://localhost:3001/api/events/5cc311c7660a1b000456eedf
Content-Type: application/json

{
  "name": "Päivitesti nimiä",
  "durationInHours": 3
}


###
DELETE http://localhost:3001/api/events/5cc311c7660a1b000456eedf