GET http://localhost:3001/api/events/

###

GET http://localhost:3001/api/events/5cc2cceae090b621d184ed0d

###

POST http://localhost:3001/api/events/
Content-Type: application/json

{
  "name": "LANIT",
  "date": "05.05.2019 15:00",
  "durationInHours": 4
}

###

PUT http://localhost:3001/api/events/5cc5f47b011d0c0004033151
Content-Type: application/json

{
  "name": "Päivitetty tapahtuma",
  "date": "005.08.1234 02:000",
  "durationInHours": 12
}


###
DELETE http://localhost:3001/api/events/5cc311c7660a1b000456eedf