GET http://localhost:3001/api/events?

###

GET https://calendar-rest-api.herokuapp.com/api/events/5cc2cceae090b621d184ed0d

###

POST http://localhost:3001/api/events
Content-Type: application/json

{
  "name": "Tapahtuma",
  "nam": "Kesdaasddasasddsasdt ",
  "date": "27.04.2019 05:00",
  "durationInHours": 3
}

###

PUT http://localhost:3001/api/events/5cc2cceae090b621d184ed0d
Content-Type: application/json

{
  "name": "Päivitetympi nimi",
  "date": "05.08.1994 05:12",
  "asd": "hei",
  "durationInHours": 3
}


###
DELETE http://localhost:3001/api/events/5cc1ee28f55e6062e212ef65